name: algolia-scraper
on:
  push:
    branches:
      - main
  check_suite:
    types: [completed]
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
      - name: scrape the site 🧽
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          WRITE_API_KEY: ${{ secrets.API_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
          INDEX_NAME: ${{ secrets.INDEX_NAME }}
        run: |
          cd .algolia
          touch .env
          ./scrape.sh
